BackEnd/Top20Video.Web/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Top20Video.Data;
using Top20Video.Framework;

namespace Top20Video.Web.Views.Settings
{
    [AuthorizeAdmin]
    public class CountriesController : Controller
    {
        private dbTop20Video_9359Entities db = new dbTop20Video_9359Entities();

        // GET: Countries
        public ActionResult Index()
        {
            return View(db.Countries.ToList());
        }

        // GET: Countries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Countries/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Code,Name,IsDefault,Status,LatLot")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(country);
        }

        // GET: Countries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Code,Name,IsDefault,Status,LatLot")] Country country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BackEnd/Top20Video.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top20Video</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="icon" href="@Url.Content("~/Content/images/favicon.png")">
    <link rel="stylesheet" href="@Url.Content("~/Content/site.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.css")" />
    @*@Styles.Render("~/Content/css")*@
    <link href="~/Content/css/headerstyle.css" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" />

    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    @*<script src="https://use.typekit.net/yrd0bpf.js"></script>
        <script>try{Typekit.load({ async: true });}catch(e){}</script>

        <!-- lato -->
        <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>*@
</head>
<body class="bodyhtml">
    @{
        string controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    }
    <section class="navigation">
        <div class="container header">
            <div class="row header_block">
                <div class="col-xs-12">
                    <nav class="navbar navbar-default header_navigation">
                        <div class="containerMobile">
                            <div class="navbar-header">
                                <button aria-expanded="false" class="navbar-toggle collapsed"
                                        data-target="#bs-example-navbar-collapse-1" data-toggle="collapse"
                                        type="button">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span> <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand adminlogo logoadjustment" href="@Url.Action("Index","Settings")">
                                    @*<img src="~/Content/images/logo-admin.png">*@
                                    Top 20 Video
                                </a>
                            </div>
                            <div class="collapse navbar-collapse navigation_main_list" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav navbar-left text_uppercase navigation_main_list_ul">
                                    @*@if (controllerName.ToLower() == "home")
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Home")' class="active-link"><span>Home</span></a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Home")'><span>Home</span></a>
                                        </li>
                                    }
                                    @if (controllerName.ToLower() == "category")
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Category")' class="active-link"><span>Category</span></a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Category")'><span>Category</span></a>
                                        </li>
                                    }
                                    @if (controllerName.ToLower() == "Video")
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Video")' class="active-link"><span>Video</span></a>
                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Video")'><span>Video</span></a>
                                        </li>
                                    }*@
                                    @if (controllerName.ToLower() == "settings")
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Settings")' class="active-link"><span>Settings</span></a>

                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Settings")'><span>Settings</span></a>

                                        </li>
                                    }
                                    @if (controllerName.ToLower() == "countries")
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Countries")' class="active-link"><span>Countries</span></a>

                                        </li>
                                    }
                                    else
                                    {
                                        <li>
                                            <a href='@Url.Action("Index","Countries")'><span>Countries</span></a>

                                        </li>
                                    }
                                </ul>
                                @if (HttpContext.Current.Session["AdminUserId"] != null)
                                {
                                    <ul class="pull-right nav navbar-nav navigation_main_list_ul">

                                        @if (controllerName.ToLower() == "changepassword")
                                        {
                                            <li>
                                                <a href='@Url.Action("Index","ChangePassword")' class="active-link"><span>CHANGE PASSWORD</span></a>
                                            </li>
                                        }
                                        else
                                        {
                                            <li>
                                                <a href='@Url.Action("Index","ChangePassword")'><span>CHANGE PASSWORD</span></a>
                                            </li>
                                        }
                                        <li>
                                            <a href='@Url.Action("Logout","Home")'>LOGOUT</a>
                                        </li>
                                    </ul>
                                }
                                else
                                {

                                }
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <div class="container body-content">
        <div style="min-height: 400px; margin-bottom:50px;">
            @RenderBody()
        </div>
        <hr />
    </div>
    <footer class="footer homeFooter">
        <div class="container containerMobile footerColor text_center">
            <ul class="left-footer leftFooterList">
                <li>© 2016 Top 20 Video</li>
            </ul>
        </div>
    </footer>

    <!-- Ajax Process Start -->
    <div class="wait-pupup">
        <div class="wait-process">
            <img src="@Url.Content("~/Content/images/ajax-loader.gif")" alt="Please wait..." />
        </div>
    </div>
    <!-- Ajax Process End -->
    <script type="text/javascript">
        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };

        $(document).ajaxComplete(function (event, request, settings) {
            $('.wait-pupup').hide();
        });
        $(document).ajaxSend(function (event, request, settings) {
            $('.wait-pupup').show();

        });
        $(document).ajaxStart(function () {
            $('.wait-pupup').show();
        });

        $('body').on('click', '.alert .close', function (e) {
            $('.alert').slideUp();
        });

        $('body').on('keypress', '.number', function (e) {
            if (e.which != 8 && e.which != 0 && e.which != 46 && (e.which < 48 || e.which > 57)) {
                return false;
            }
            else
                return true;
        });
        function redirect(toUrl) {
            window.location = toUrl;
        }
        function refreshAfterOrder() {
            var pcount = $('.page-no span.active').length;
            if (pcount > 0) {
                var pNo = $('.page-no span.active').html();
                pageRequest(pNo);
            }
            else {
                asynList();
            }
        }
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

BackEnd/Top20Video.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="@Url.Content("~/Content/site.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.css")" />
    @*@Styles.Render("~/Content/css")*@
    <link href="~/Content/css/headerstyle.css" rel="stylesheet">
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet" />

</head>
<body>
    <section class="navigation">
        <div class="container header">
            <div class="row header_block">
                <div class="col-xs-12">
                    <nav class="navbar navbar-default header_navigation">
                        <div class="containerMobile">
                            <div class="navbar-header">
                                <button aria-expanded="false" class="navbar-toggle collapsed"
                                        data-target="#bs-example-navbar-collapse-1" data-toggle="collapse"
                                        type="button">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span> <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button> <a class="navbar-brand adminlogo logoadjustment" >
                                    @*<img src="~/Content/images/logo-admin.png">*@
                                              Top 20 Video
                                </a>
                            </div>
                        </div>
                    </nav>
                </div>
            </div> 
        </div>
    </section>
    <section class="bg-image">
        @RenderBody()
    </section>

    <!-- Ajax Process Start -->
    <div class="wait-pupup">
        <div class="wait-process">
            <img src="@Url.Content("~/Content/images/ajax-loader.gif")" alt="Please wait..." />
        </div>
    </div>
    <!-- Ajax Process End -->
    <!-- Ajax Process End -->
    <script type="text/javascript">


        function preventBack() { window.history.forward(); }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };

        $(document).ajaxComplete(function (event, request, settings) {
            $('.wait-pupup').hide();
        });
        $(document).ajaxSend(function (event, request, settings) {
            $('.wait-pupup').show();

        });
        $(document).ajaxStart(function () {
            $('.wait-pupup').show();
        });

        $('body').on('click', '.alert .close', function (e) {
            $('.alert').slideUp();
        });

        $('body').on('keypress', '.number', function (e) {
            if (e.which != 8 && e.which != 0 && e.which != 46 && (e.which < 48 || e.which > 57)) {
                return false;
            }
            else
                return true;
        });
        function redirect(toUrl) {
            window.location = toUrl;
        }
    </script>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>

</html>